// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gdkkzfapynitcmkmtoze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdka2t6ZmFweW5pdGNta210b3plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMDA0ODAsImV4cCI6MjA4NzY3NjQ4MH0.AopO0PuCivzsuruQDYRPm3mDPfrUgJaheYqNCOuT_tk";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);